services:
  codephp:
    # image: coderphp:8.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
      - MYSQL_DATABASE=codephp
      - MYSQL_USER=codephp
      - MYSQL_PASSWORD=adminadmin
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_USERNAME=codephp
      - ADMINER_PASSWORD=adminadmin
    depends_on:
      - db
      
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_USER=codephp
  #     - PMA_PASSWORD=adminadmin
  #   ports:
  #     - 8081:80
  #   restart: unless-stopped


